dayly_min: 55
dayly_max: 130
min_days: 18
max_days: 28
start_at: 23
pages_needed: 1
page: 1
month_nr: 1
month: Styczeń
year: 2023
first_day_date : 1.01.2023
last_day_date : 31.01.2023
car_register_numbers: GD 004WP
first_day_value: 96183
last_day_value: 98462
car_name: Skoda Fabia